apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1
  tags: {environment: staging}
nodeGroups:
  - name: kube-cluster-ng-1
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
    iam:
      withAddonPolicies:
        autoScaler: true
  - name: kube-cluster-ng-2
    labels:
      nodegroup-type: frontend-workloads
    instanceType: t3.small
    minSize: 1
    maxSize: 2
    availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        fsx: true
        efs: true
