apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: us-east-1
  tags: {environment: staging}
nodeGroups:
  - name: kube-cluster-ng-1
    labels:
      nodegroup-type: backend-workloads
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
  #  availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
  - name: kube-cluster-ng-2
    labels:
      nodegroup-type: frontend-workloads
    instanceType: t3.small
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
 #   availabilityZones: ["us-east-1a", "us-east-1b"]
    ami: auto
    volumeSize: 50
    ssh: # use existing EC2 key
      publicKeyName: ec2_dev_key
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true
